site_name: PhotoScript Docs
site_url: https://rhettbull.github.io/photoscript/
nav:
    - Home: index.md
    - Reference: reference.md
plugins:
    - search
    - mkdocstrings
theme:
    name: material
