""" Test configuration data for the test suite; returns data specific to the macOS version under test. """

import pytest

from photoscript.utils import get_os_version

# These imports could be handled in a less verbose way using importlib but
# I want to be able to see values of the constants in the editor
# so importing them explicitly is easier makes this easier
OS_VER = get_os_version()
if OS_VER[0] == 10 and OS_VER[1] == 15:
    from tests.photoscript_config_catalina import (
        ALBUM_1_NAME,
        ALBUM_1_PATH_STR,
        ALBUM_1_PATH_STR_COLON,
        ALBUM_1_PHOTO_EXPORT_FILENAMES,
        ALBUM_1_PHOTO_UUIDS,
        ALBUM_1_POST_REMOVE_UUIDS,
        ALBUM_1_REMOVE_UUIDS,
        ALBUM_1_UUID,
        ALBUM_1_UUID_OSXPHOTOS,
        ALBUM_NAMES_ALL,
        ALBUM_NAMES_TOP,
        EMPTY_ALBUM_NAME,
        FIND_FILES,
        FOLDER_1_IDSTRING,
        FOLDER_1_LEN,
        FOLDER_1_NAME,
        FOLDER_1_SUBFOLDERS,
        FOLDER_1_UUID,
        FOLDER_1_UUID_OSXPHOTOS,
        FOLDER_2_LEN,
        FOLDER_2_NAME,
        FOLDER_2_PATH,
        FOLDER_2_PATH_STR,
        FOLDER_2_PATH_STR_COLON,
        FOLDER_2_UUID,
        FOLDER_3_ALBUMS,
        FOLDER_3_LEN,
        FOLDER_3_NAME,
        FOLDER_3_UUID,
        FOLDER_NAME,
        FOLDER_NAMES_ALL,
        FOLDER_NAMES_TOP,
        FOLDER_UUID,
        IMPORT_PATHS,
        IMPORT_PHOTOS,
        NUM_PHOTOS,
        PHOTO_ADD_UUID,
        PHOTO_EXPORT_2_FILENAMES,
        PHOTO_EXPORT_2_FILENAMES_ORIGINAL,
        PHOTO_EXPORT_FILENAME,
        PHOTO_EXPORT_FILENAME_ORIGINAL,
        PHOTO_EXPORT_UUID,
        PHOTO_FAVORITES_SET_UUID,
        PHOTO_FAVORITES_UNSET_UUID,
        PHOTOS_DICT,
        PHOTOS_FAVORITES,
        PHOTOS_FAVORITES_SET,
        PHOTOS_FILENAMES,
        PHOTOS_PLANTS,
        PHOTOS_UUID,
        PHOTOS_UUID_FILENAMES,
        SELECTION_UUIDS,
        TEST_LIBRARY,
        TEST_LIBRARY_OPEN,
    )
elif OS_VER[0] == 13:
    from tests.photoscript_config_ventura import (
        ALBUM_1_NAME,
        ALBUM_1_PATH_STR,
        ALBUM_1_PATH_STR_COLON,
        ALBUM_1_PHOTO_EXPORT_FILENAMES,
        ALBUM_1_PHOTO_UUIDS,
        ALBUM_1_POST_REMOVE_UUIDS,
        ALBUM_1_REMOVE_UUIDS,
        ALBUM_1_UUID,
        ALBUM_1_UUID_OSXPHOTOS,
        ALBUM_NAMES_ALL,
        ALBUM_NAMES_TOP,
        EMPTY_ALBUM_NAME,
        FIND_FILES,
        FOLDER_1_IDSTRING,
        FOLDER_1_LEN,
        FOLDER_1_NAME,
        FOLDER_1_SUBFOLDERS,
        FOLDER_1_UUID,
        FOLDER_1_UUID_OSXPHOTOS,
        FOLDER_2_LEN,
        FOLDER_2_NAME,
        FOLDER_2_PATH,
        FOLDER_2_PATH_STR,
        FOLDER_2_PATH_STR_COLON,
        FOLDER_2_UUID,
        FOLDER_3_ALBUMS,
        FOLDER_3_LEN,
        FOLDER_3_NAME,
        FOLDER_3_UUID,
        FOLDER_NAME,
        FOLDER_NAMES_ALL,
        FOLDER_NAMES_TOP,
        FOLDER_UUID,
        IMPORT_PATHS,
        IMPORT_PHOTOS,
        NUM_PHOTOS,
        PHOTO_ADD_UUID,
        PHOTO_EXPORT_2_FILENAMES,
        PHOTO_EXPORT_2_FILENAMES_ORIGINAL,
        PHOTO_EXPORT_FILENAME,
        PHOTO_EXPORT_FILENAME_ORIGINAL,
        PHOTO_EXPORT_UUID,
        PHOTO_FAVORITES_SET_UUID,
        PHOTO_FAVORITES_UNSET_UUID,
        PHOTOS_DICT,
        PHOTOS_FAVORITES,
        PHOTOS_FAVORITES_SET,
        PHOTOS_FILENAMES,
        PHOTOS_PLANTS,
        PHOTOS_UUID,
        PHOTOS_UUID_FILENAMES,
        SELECTION_UUIDS,
        TEST_LIBRARY,
        TEST_LIBRARY_OPEN,
    )
else:
    pytest.exit("This test suite does not run on this version of MacOS")


__all__ = [
    "ALBUM_1_NAME",
    "ALBUM_1_PATH_STR",
    "ALBUM_1_PATH_STR_COLON",
    "ALBUM_1_PHOTO_EXPORT_FILENAMES",
    "ALBUM_1_PHOTO_UUIDS",
    "ALBUM_1_POST_REMOVE_UUIDS",
    "ALBUM_1_REMOVE_UUIDS",
    "ALBUM_1_UUID",
    "ALBUM_1_UUID_OSXPHOTOS",
    "ALBUM_NAMES_ALL",
    "ALBUM_NAMES_TOP",
    "EMPTY_ALBUM_NAME",
    "FIND_FILES",
    "FOLDER_1_IDSTRING",
    "FOLDER_1_LEN",
    "FOLDER_1_NAME",
    "FOLDER_1_SUBFOLDERS",
    "FOLDER_1_UUID",
    "FOLDER_1_UUID_OSXPHOTOS",
    "FOLDER_2_LEN",
    "FOLDER_2_NAME",
    "FOLDER_2_PATH",
    "FOLDER_2_PATH_STR",
    "FOLDER_2_PATH_STR_COLON",
    "FOLDER_2_UUID",
    "FOLDER_3_ALBUMS",
    "FOLDER_3_LEN",
    "FOLDER_3_NAME",
    "FOLDER_3_UUID",
    "FOLDER_NAME",
    "FOLDER_NAMES_ALL",
    "FOLDER_NAMES_TOP",
    "FOLDER_UUID",
    "IMPORT_PATHS",
    "IMPORT_PHOTOS",
    "NUM_PHOTOS",
    "PHOTOS_DICT",
    "PHOTOS_FAVORITES",
    "PHOTOS_FAVORITES_SET",
    "PHOTOS_FILENAMES",
    "PHOTOS_PLANTS",
    "PHOTOS_UUID",
    "PHOTOS_UUID_FILENAMES",
    "PHOTO_ADD_UUID",
    "PHOTO_EXPORT_2_FILENAMES",
    "PHOTO_EXPORT_2_FILENAMES_ORIGINAL",
    "PHOTO_EXPORT_2_FILENAMES_ORIGINAL",
    "PHOTO_EXPORT_FILENAME",
    "PHOTO_EXPORT_FILENAME_ORIGINAL",
    "PHOTO_EXPORT_UUID",
    "PHOTO_FAVORITES_SET_UUID",
    "PHOTO_FAVORITES_UNSET_UUID",
    "SELECTION_UUIDS",
    "TEST_LIBRARY",
    "TEST_LIBRARY_OPEN",
]
